from Classes import *

def main():
    print("Bem vindo ao Birdspédia")
    print("[01] - Águia")
    print("[02] - Albatroz")
    print("[03] - Avestruz")
    print("[04] - Beija-flor")
    print("[05] - Bico-de-Tamanco")
    print("[06] - Casuar")
    print("[07] - Cegonha")
    print("[08] - Codorna")
    print("[09] - Coruja")
    print("[10] - Ema")
    print("[11] - ")
    print("[12] - ")
    print("[13] - ")
    print("[14] - ")
    print("[15] - ")
    print("[16] - ")
    print("[17] - ")
    print("[18] - ")
    print("[19] - ")
    print("[20] - ")
    print("[21] - ")
