from Classes import *

def main():
    print("Bem vindo ao Birdspédia")
    print("[01] - Águia")
    print("[02] - Albatroz")
    print("[03] - Avestruz")
    print("[04] - Beija-flor")
    print("[05] - Bico-de-Tamanco")
    print("[06] - Casuar")
    print("[07] - Cegonha")
    print("[08] - Codorna")
    print("[09] - Coruja")
    print("[10] - Ema")
    print("[11] - Falcão")
    print("[12] - Gaivota")
    print("[13] - Galinha")
    print("[14] - Gavião")
    print("[15] - Kiwi")
    print("[16] - Pato")
    print("[17] - Pavão")
    print("[18] - Pelicano")
    print("[19] - Pica-Pau")
    print("[20] - Pinguim")
    print("[21] - Tucano")
