from Classes import *

def main():
    while True:
        try:            
            print("Bem vindo ao Birdspédia.")
            print("[01] - Águia")
            print("[02] - Albatroz")
            print("[03] - Avestruz")
            print("[04] - Beija-flor")
            print("[05] - Bico-de-Tamanco")
            print("[06] - Casuar")
            print("[07] - Cegonha")
            print("[08] - Codorna")
            print("[09] - Coruja")
            print("[10] - Ema")
            print("[11] - Falcão")
            print("[12] - Gaivota")
            print("[13] - Galinha")
            print("[14] - Gavião")
            print("[15] - Kiwi")
            print("[16] - Pato")
            print("[17] - Pavão")
            print("[18] - Pelicano")
            print("[19] - Pica-Pau")
            print("[20] - Pinguim")
            print("[21] - Tucano")
            print("[22] - Sair")
            menu=input("Digite o número correspondente à ave que gostaria de visitar.")
            
            match menu:
                case 1:
                    aguia = Aguia()
                    aguia.botarOvo()
                    aguia.pena()
                    aguia.bico()
                    aguia.voar()
                    aguia.informações()
                case 2:
                    albatroz = Albatroz()
                    albatroz.botarOvo()
                    albatroz.pena()
                    albatroz.bico()
                    albatroz.voar()
                    albatroz.informações()
                case 3:
                    avestruz = Avestruz()
                    avestruz.botarOvo()
                    avestruz.pena()
                    avestruz.bico()
                    avestruz.nãovoar()
                    avestruz.informações()
                case 4:
                    beijaflor = BeijaFlor()
                    beijaflor.botarOvo()
                    beijaflor.pena()
                    beijaflor.bico()
                    beijaflor.voar()
                    beijaflor.informações()
                case 5:
                    bicotamanco = Bico_de_Tamanco()
                    bicotamanco.botarOvo()
                    bicotamanco.pena()
                    bicotamanco.bico()
                    bicotamanco.nãovoar()
                    bicotamanco.informações()
                case 6:
                    causar = Casuar()
                    causar.botarOvo()
                    causar.pena()
                    causar.bico()
                    causar.nãovoar()
                    causar.informações()
                case 7:
                    cegonha = Cegonha()
                    cegonha.botarOvo()
                    cegonha.pena()
                    cegonha.bico()
                    cegonha.voar()
                    cegonha.informações()
                case 8:
                    codorna = Codorna()
                    codorna.botarOvo()
                    codorna.pena()
                    codorna.bico()
                    codorna.nãovoar()
                    codorna.informações()
                case 9:
                    coruja = Coruja()
                    coruja.botarOvo()
                    coruja.pena()
                    coruja.bico()
                    coruja.voar()
                    coruja.informações()
                case 10:
                    ema = Ema()
                    ema.botarOvo()
                    ema.pena()
                    ema.bico()
                    ema.nãovoar()
                    ema.informações()
                case 11:
                    falcão = Falcão()
                    falcão.botarOvo()
                    falcão.pena()
                    falcão.bico()
                    falcão.voar()
                    falcão.informações()
                case 12:
                    gaivota = Gaivota()
                    gaivota.botarOvo()
                    gaivota.pena()
                    gaivota.bico()
                    gaivota.voar()
                    gaivota.informações()
                case 13:
                    galina = Galinha()
                    galina.botarOvo()
                    galina.pena()
                    galina.bico()
                    galina.nãovoar()
                    galina.informações() 
                case 14:
                    gavião = Gavião()
                    gavião.botarOvo()
                    gavião.pena()
                    gavião.bico()
                    gavião.voar()
                    gavião.informações()
                case 15:
                    kiwi = Kiwi()
                    kiwi.botarOvo()
                    kiwi.pena()
                    kiwi.bico()
                    kiwi.nãovoar()
                    kiwi.informações() 
                case 16:
                    pato = Pato()
                    pato.botarOvo()
                    pato.pena()
                    pato.bico()
                    pato.voar()
                    pato.informações()
                case 17:
                    pavão = Pavão()
                    pavão.botarOvo()
                    pavão.pena()
                    pavão.bico()
                    pavão.nãovoar()
                    pavão.informações ()
                case 18:
                    pelicano = Pelicano()
                    pelicano.botarOvo()
                    pelicano.pena()
                    pelicano.bico()
                    pelicano.voar()
                    pelicano.informações()
                case 19:
                    picapau = PicaPau()
                    picapau.botarOvo()
                    picapau.pena()
                    picapau.bico()
                    picapau.voar()
                    picapau.informações()
                case 20:
                    pinguim = Pinguim()
                    pinguim.botarOvo()
                    pinguim.pena()
                    pinguim.bico()
                    pinguim.nãovoar()
                    pinguim.informações() 
                case 21:
                    tucano = Tucano()
                    tucano.botarOvo()
                    tucano.pena()
                    tucano.bico()
                    tucano.voar()
                    tucano.informações()
                case 22:
                    exit()
                case _:
                    print ("Opção inválida.")        
        
        except:
            print("Erro, opção inválida. Tente novamente.")